[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-store, max-age=0, must-revalidate"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-store, max-age=0, must-revalidate"

[[headers]]
  for = "/404.html"
  [headers.values]
    Cache-Control = "no-store, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"
